### ISSUE TITLE
Determine research direction

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-web-crawler#18]
It turned out to be difficult to use the VPN for different countries. Here are a few options to try:

- Ask @katehausladen if she has some insight (@danielgoldelman)  
- Different VPN (e.g., Nord VPN) (@dadak-dom, @natelevinson10, and @JoeChampeau) 
- Different countries/regions (@dadak-dom, @natelevinson10, and @JoeChampeau) 
- Google Cloud (@natelevinson10) 
- Investigating network layer to check what is up (WireShark etc.) (@danielgoldelman)

**Comment by katehausladen** [comment]
> Ask @katehausladen if she has some insight

I have only used the Mullvad VPN in Los Angeles for crawling. I haven't ever used it for other countries. My only suggestion would be trying multiple different IP addresses in the same location if the VPN has more than one.

**Comment by SebastianZimmeck** [comment]
Thanks, @katehausladen!

Indeed, it seems like the GPC crawl is different than the Privacy Pioneer crawl. @danielgoldelman will describe a bit more the problem to you and maybe you can think of additional ideas. This is just in case.

**Comment by JoeChampeau** [comment]
As discussed during the meeting, trying out anyIP's static residential proxies didn't bear any fruit. Seems like proxies in general may not be able to offer any advantages over cloud computing or VPNs, although it might still be worth trying out what @natelevinson10 found.

**Comment by dadak-dom** [comment]
I've been running test crawls on the Google Cloud VM. As @danielgoldelman mentioned, the cloud option provides a significant improvement for location elements, but performs worse for the analytics category. As discussed in the meeting, I'll start looking into what could possibly be going wrong here.

**Comment by natelevinson10** [comment]
Similarly to @JoeChampeau , I also tested static ISP proxies from the provider Bright Proxies and found that they did not offer and advantages either. With these findings, we can likely close the door on the possibility of using web scraping proxies to test the crawler.

**Comment by SebastianZimmeck** [comment]
Sounds good, @natelevinson10!
