### ISSUE TITLE
Swap some locations due to Google Cloud Switch

### ISSUE THREAD

**Issue by dadak-dom** [privacy-tech-lab/privacy-pioneer-web-crawler#19]
@danielgoldelman brought to my attention that there's some locations that we were planning on crawling, but are not listed as locations in Google Cloud. This is unfortunate, but it's a necessary side effect of issue #17 . I've come up with some replacement ideas and will work on generating the new crawl lists. This shouldn't interfere with testing.

The locations that will need to be replaced: 
Denver
Ukraine
New Zealand
Ireland

My suggestions:
Dallas (privacy law enacted in 2023, and could be a good comparison with California since the general public seems to care a lot about Texas vs. California anecdotally) 
India (privacy law is only about a year old)
Canada (has a privacy law in the works, although it hasn't been passed yet)
Germany (has it's own legislation in addition to GDPR)

@SebastianZimmeck, please let me know if you think these are good replacements so that we can test with these locations and make the replacement lists. Also feel free to suggest alternatives, of course.

**Comment by SebastianZimmeck** [comment]
Yes, assuming that the tests work, these new locations are good.

**Comment by SebastianZimmeck** [comment]
I assume they do not have Australia or some other Oceania? Just trying to cover different continents.

**Comment by dadak-dom** [comment]
> I assume they do not have Australia or some other Oceania? Just trying to cover different continents.

Australia we have, so Oceania is covered. 👍

**Comment by dadak-dom** [comment]
All crawl lists have been updated. Closing this issue.
