### ISSUE TITLE
Issue with reloading ML in Firefox after Recompiling Extension

### ISSUE THREAD

**Issue by JoeChampeau** [privacy-tech-lab/privacy-pioneer-web-crawler#20]
@danielgoldelman found a bug with the Google Cloud VM wherein old ML models would remain cached in Firefox when running crawls, causing location classifiers to fail when loading in a new .xpi of the extension. We should look for a way to consistently reset this to ensure the proper ML model is always being loaded.

**Comment by SebastianZimmeck** [comment]
And @danielgoldelman will document this somewhere (TBD) so that @dadak-dom and @natelevinson10 know what to do.

**Comment by JoeChampeau** [comment]
The major issue with loading in the ML should be fixed now, and crawls seem to be detecting location just fine. Will be linking a PR soon.
