### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-web-crawler#23]
Once the crawler stands, we should create a release.

**Comment by SebastianZimmeck** [comment]
After the testing, we should create one release to mark it as the one with which we tested (and with which we crawl). (#9)

**Comment by SebastianZimmeck** [comment]
Before the crawl (#62), @PattonYin and @harry will prepare a release with the version of the crawler (v1.0.0) used in the crawl.

The changes over the last few months that @atlasharry and @PattonYin made are in both the crawler and the standalone Privacy Pioneer extension. Both are in sync at this point.

**Comment by atlasharry** [comment]
We created our release [here](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/releases/tag/v1.0.0), so this issue will be closed.
