### ISSUE TITLE
Refactor Crawler Branches

### ISSUE THREAD

**Issue by JoeChampeau** [privacy-tech-lab/privacy-pioneer-web-crawler#26]
We're currently maintaining several different branches, some of which only differ in the XPIs they implement, and some of which have slight differences in functionality. We should take some time to eliminate outdated branches and work out a more logical organizational strategy.

**Comment by SebastianZimmeck** [comment]
Good point! Ultimately, we should only have one authoritative branch, `main`.

**Comment by SebastianZimmeck** [comment]
@dadak-dom, as you will be doing the crawl, please also get involved and huddle with @JoeChampeau on how to fix this issue.

**Comment by dadak-dom** [comment]
@SebastianZimmeck @JoeChampeau My understanding was that #25 will resolve this issue. Once I'm confident that my code works, we can merge everything test-related into issue-9. Will update once that's all set.

**Comment by JoeChampeau** [comment]
@dadak-dom #25 is part of the issue, but we also have branches that differ on the actual JS they implement, so we also need to  ensure we identify the most updated branches (I had thought it was one of the `issue-18` branches, but it could also be `issue-9`) and merge/purge the rest.

**Comment by SebastianZimmeck** [comment]
Per @dadak-dom the issue-9 branch is the most recent one that should have all the features. Merging that branch should resolve this issue. @dadak-dom will open a PR and @JoeChampeau will review it.

**Comment by dadak-dom** [comment]
Relevant PR has been merged 👍
