### ISSUE TITLE
Update readme as necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-web-crawler#43]
As @atlasharry was trying to install the crawler he ran into difficulties, especially, with the [REST API part](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler?tab=readme-ov-file#3-instructions-for-running-the-crawler).

@atlasharry and @dadak-dom, can you find out what went wrong and update the readme, as necessary?

**Comment by atlasharry** [comment]
Hi @SebastianZimmeck @dadak-dom, I have updated the readme based on my experience setting up the crawler, please feel free to make any changes on my editions.

**Comment by SebastianZimmeck** [comment]
Thanks, @atlasharry!

As the readme stands now after your changes, you were able to set up the crawler and it works properly?

**Comment by dadak-dom** [comment]
@atlasharry , your changes look good to me 👍 . I've also updated/removed some outdated parts.

**Comment by SebastianZimmeck** [comment]
Excellent, @atlasharry and @dadak-dom!

**Comment by atlasharry** [comment]
> Thanks, @atlasharry!
> 
> As the readme stands now after your changes, you were able to set up the crawler and it works properly?

Yes! With Dominik's help, I have set up the crawler and it works perfect on my end.
