### ISSUE TITLE
Programmatically turn off enhanced data tracking protection

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-web-crawler#45]
To see the largest number of trackers, we need to turn off Enhance Tracking Protection in Firefox. As discussed, @dadak-dom will change the crawler to that effect and make an explanatory note in the crawler readme. Good find, @dadak-dom!

**Comment by dadak-dom** [comment]
Will be closed via #46. 

Interestingly, the latest version of Firefox Nightly seems to have broken the ability to find monetization requests. Manually installing an older version seems to fix it. I've updated the readme with that information as well.

**Comment by dadak-dom** [comment]
Relevant PR has been merged.
