### ISSUE TITLE
Create South Korea crawl list

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-web-crawler#50]
As we will be testing (issue #9) on South Korea since @atlasharry will be there and there is a South Korea Google VM, it makes sense to also include South Korean sites in the crawl.

@atlasharry will create such list with 525 sites similar to the other [crawl lists](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/tree/main/selenium-crawler/crawl-lists) according to @dadak-dom's protocol. @dadak-dom will provide input on how to create this list.

**Comment by atlasharry** [comment]
South Korea's top 525 list is now uploaded to branch 50, along with some scripts to build this list. I will merge this branch into branch 51-prepare-crawler-test-list to make the final test

**Comment by SebastianZimmeck** [comment]
Sounds good, @atlasharry! Feel free to close this issue if there is nothing more to do.
