### ISSUE TITLE
Prepare Crawler Test List

### ISSUE THREAD

**Issue by atlasharry** [privacy-tech-lab/privacy-pioneer-web-crawler#51]
I have created a new 100-site crawler test list. It is located selenium-crawler\Sites_Preparation folder

**Comment by atlasharry** [comment]
I have added South Korea sites to the final 100 test list in [this](https://github.com/privacy-tech-lab/privacy-pioneer-web-crawler/commit/e0527debf31e2a1020d032237f1689081fae75f5) commit.

**Comment by SebastianZimmeck** [comment]
Feel free to close once all work is done, @atlasharry.

**Comment by atlasharry** [comment]
This issue is done!
